### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by fasogbon** [4lphachain/Pumpfun_Solana_Sniper_Bot#2]
Thabks for the work, do you know why i am having the following error please?
![image](https://github.com/user-attachments/assets/b6c27378-ab40-4819-9c9c-ca732acffa8a)

**Comment by 4lphachain** [comment]
hi, there are some errors. i have updated it

**Comment by fasogbon** [comment]
SCAM

**Comment by fasogbon** [comment]
SCAM!!
